plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

#npmScopes:
#  cattr:
#    npmRegistryServer: "https://git.amazingcat.net/api/v4/packages/npm/"
#    npmPublishRegistry: "https://git.amazingcat.net/api/v4/projects/359/packages/npm/"
#    npmAuthToken: "${CI_JOB_TOKEN-fallback}"
npmScopes:
  cattr:
    npmRegistryServer: " https://registry.npmjs.org"
    npmPublishRegistry: " https://registry.npmjs.org"
    npmAuthToken: "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"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
